[server]
	Host = "https://matrix.works/"
	ListenAddress = "127.0.0.1"
	ListenPort = 4000
	LogFile = "fgw.log"

	SysTimeForm = "2004-08-01 15:04:05"   # 时间转换格式
	SysDateForm = "2004-08-01"       # 日期转换格式
	SysTimeZone = "Asia/Shanghai"

	SignSecret = "******"
	CookieSecret = "??????"

	AppId = "my_app"
	AppToken = "my_app_token"

[UrlPermission]
	UrlWhiteList = [
    "/",
    "/system",
    "/user/login",
    "/user/register",
    "/user/register_confirm",
    "/user/exists",
    "/user/email_exists",
    "/user/require_authcode",
    "/user/verify_authcode",
    "/user/reset_password",
    "/user/settings/languagelist",
	]
	UrlPrefixWhiteList = [
    "/market",
	]
	UrlUserAccessList = [
    "/user",
    "/upload",
	]

[RouteTable]
  "/user" = "http://localhost:4010/"      # user center service (fuc)
  "/query" = "http://localhost:4020/"     # data query service (fdq)

[redises]
  [redises.default]
		host = "127.0.0.1"
		port = 6600
		database = 0

[misc]
  GuestUserId = 0
